spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/main
    user: postgres
    password: mysecretpassword
    locations: classpath:db/migration
smartReplication:
  enabled: true
  kafka:
    autoconfiguration: false
  etcd:
    enabled: true
    connectTimeoutMs: 5000
    endpoints:
      - https://localhost:2379
    pem:
      ca-cert-path: etcd-tls-docker/client-certs/ca.crt
      private-key-path: etcd-tls-docker/client-certs/client.key
      cert-chain-path: etcd-tls-docker/client-certs/client.crt
  producer:
    mainDatasource:
      url: jdbc:postgresql://localhost:5432/main
      username: postgres
      password: mysecretpassword
      maxPoolSize: 10
      schema: schema1
    standinDatasource:
      url: jdbc:postgresql://localhost:5432/standin
      username: postgres
      password: mysecretpassword
      maxPoolSize: 10
      schema: schema1
    kafkaConnectionString: localhost:9092
    owner: towner
    shouldStopReplication: false
    replicationEnabled: true
    maxReplicationErrors: 0
    errorPeriodInSeconds: 120
application:
  defaultDataSource:
    url: jdbc:postgresql://localhost:5432/main
    username: postgres
    password: mysecretpassword
    maxPoolSize: 10
    schema: schema1

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure.include: health,prometheus
  endpoint:
    health:
      show-details: always
      enabled: true
      probes.enabled: true
    prometheus.enabled: true
logging:
  level:
    test:
      dev:
        smartreplication: DEBUG

    org:
      apache:
        kafka: INFO
      springframework: INFO

