spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/main
    user: postgres
    password: mysecretpassword
    locations: classpath:db/migration
smartReplication:
  enabled: true
  kafka:
    autoconfiguration: false
  etcd:
    enabled: true
    connectTimeoutMs: 5000
    endpoints:
      - https://localhost:2379
    pem:
      ca-cert-path: etcd-tls-docker/client-certs/ca.crt
      private-key-path: etcd-tls-docker/client-certs/client.key
      cert-chain-path: etcd-tls-docker/client-certs/client.crt
  producer:
    mainDatasource:
      url: jdbc:postgresql://localhost:5432/main
      username: postgres
      password: mysecretpassword
      maxPoolSize: 10
      schema: schema1
    standinDatasource:
      url: jdbc:postgresql://localhost:5432/standin
      username: postgres
      password: mysecretpassword
      maxPoolSize: 10
      schema: schema1
    mainDatasource2:
      url: jdbc:postgresql://localhost:5432/main2
      username: postgres
      password: mysecretpassword
      maxPoolSize: 10
      schema: schema2
    standinDatasource2:
      url: jdbc:postgresql://localhost:5432/standin2
      username: postgres
      password: mysecretpassword
      maxPoolSize: 10
      schema: schema2
    kafkaConnectionString: localhost:9092
    owner: towner
    owner2: towner2
    shouldStopReplication: false
    replicationEnabled: true
    maxReplicationErrors: 0
    errorPeriodInSeconds: 120
    elasticRoutingEnabled: true
application:
  defaultDataSource:
    url: jdbc:postgresql://localhost:5432/main
    username: postgres
    password: mysecretpassword
    maxPoolSize: 10
    schema: schema1

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure.include: health,prometheus
  endpoint:
    health:
      show-details: always
      enabled: true
      probes.enabled: true
    prometheus.enabled: true
logging:
  level:
    test:
      dev:
        smartreplication: DEBUG
    org:
      apache:
        kafka: INFO
      springframework: INFO
elastic-routing-client:
  service-names: TESTTSAJTSSG
  http:
    uri: elastic-routing-consumer-st.apps.ds5-otpl01.corp.dev.dev
    tls:
      enable: true
      keystore-path: /Users/iantipova/infra/tsaj_dev_otpl_kafka/client-keystore.p12
      truststore-path: /Users/iantipova/infra/tsaj_dev_otpl_kafka/truststore.p12
      keystore-password: tsajdev
      truststore-password: tsajdev
  kafka:
    bootstrap-servers: d6tssg-kfc001lk.corp.dev.dev:9092,d6tssg-kfc002lk.corp.dev.dev:9092,d6tssg-kfc003lk.corp.dev.dev:9092
    topics: routeTemplateTopic_TESTTSAJTSSG_DICTIONARY,routeTemplateTopic_TESTTSAJTSSG_DATABASE
    group-id: testtsajtssg-group-id
    tls:
      enable: true
      truststore-path: /Users/iantipova/infra/tsaj_dev_otpl_kafka/truststore.p12
      truststore-password: tsajdev
      keystore-path: /Users/iantipova/infra/tsaj_dev_otpl_kafka/client-keystore.p12
      keystore-password: tsajdev
